### PR TITLE
Content rendering was rewritten to support multiple template engines.

### PR DESCRIPTION
**Pull request by toshka**
Content did not rendered if several template engines are configured in Django application.
It raises exception during call get_template().
I have replaced content rendering with render_to_string() function.

### CODE REVIEW

**Comment by djsutho** [comment]
@toshka what is the set-up that is causing this? Is having django templates and jinja templates at the same time, only with jinja or something else?

Also is to possible to avoid adding to `INSTALLED_APPS` as I would like to keep set-up requirements to a minimum?

**Comment by toshka** [comment]
@djsutho I need to limit some templates of context processors usage. Here is my TEMPLATES config:

```
TEMPLATES = [
    {
        'NAME': 'libs',
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'myproject/lib_templates')],
        'APP_DIRS': False,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
            ],
        },
    },
    {
        'NAME': 'forms',
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(ROOT, 'templates')],
        'APP_DIRS': False,
    },
    {
        'NAME': 'default',
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'myproject/templates'), os.path.join(BASE_DIR, 'frontend/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.template.context_processors.request',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    }
]
```
I'm understand your desire to leave minimal setup but if you want clean code it is the only one solution to add application to `INSTALLED_APPS`. All other solutions I found is too dirty or can cause additional problems.

**Comment by SalahAdDin** [comment]
:+1:

**Comment by djsutho** [comment]
@toshka I've pushed up a branch. Can you try installing it with:
```
pip install --no-deps -U git+https://github.com/djsutho/django-debug-toolbar-request-history.git@multi-templates
```
and see if it fixes the issue?

**Comment by toshka** [comment]
@djsutho yes, it is works

**Pull request closed without merging**
