### PR TITLE
fix: invalidate jquery data cache when setting store-id (for django-debug-toolbar < 1.10)

### PR DESCRIPTION
**Pull request by laffuste**
Fixes issue: https://github.com/djsutho/django-debug-toolbar-request-history/issues/25

### CODE REVIEW

**Comment by djsutho** [comment]
Thanks for the PR. I'm currently on holiday so won't be able to look at this for at least a week.

**Comment by laffuste** [comment]
No hurries, enjoy your time off ;)

**Comment by djsutho** [comment]
I'm having trouble replicating the issue with a simple app in a clean virtualenv running ` pip install -U django-debug-toolbar-request-history  django-debug-toolbar==1.9.1  Django==1.8.19` for required dependencies.

I'm not totally adverse to merging before replicating but is it possible to provide a simple demo app? 

Another option might be to try installing a version that worked with django-debug-toolbar==1.9.1 e.g.:

```sh
pip install -U django-debug-toolbar-request-history==0.0.7
```

Otherwise I have a question about the ordering of the `removeData` part. Without being able to test it my impression is that the `removeData` call should occur before the `.setAttribute('data-store-id', id)` so that it's not removed. Another option would be to set it with jQuery if available e.g.:

```js
if (djdt && djdt.jQuery) {  // using django-debug-toolbar < 1.10?
   djdt.jQuery('#djDebug').data('store-id', id);
} else {
    document.querySelector('#djDebug').setAttribute('data-store-id', id);
}
```

Let me know what you think.

**Comment by djsutho** [comment]
@laffuste Have you had a chance to look at this?

**Comment by laffuste** [comment]
Sorry about the delay, I completely forgot about this!

Here is a repro example:
https://github.com/laffuste/ddt_hr_issue25_repro
(Private because it's non relevant to anybody)

**Comment by laffuste** [comment]
About the order of the lines, I believe it doesn't matter. 
As stated in the [jQuery docs](https://api.jquery.com/removeData/): 

> Note that .removeData() will only remove data from jQuery's internal .data() cache, and any corresponding data- attributes on the element will not be removed.

You can think of it as a "clearCache(prop)" or "invalidateCache(prop)". Next time jQuery attempts to retireve the value, there will be a cache miss and it is forced to retrieve it from dom's data attribute (and cache it again).

The problem happens because django-debug-toolbar < 1.10 still uses jQuery and retrieves the attribute with `data()`, which checks into his cache. Since request-header sets the value drectly to the dom without passing by jquery, the second time django-debug-toolbar < 1.10 retrieves the store-id it's still the first cached value.

An alternative of course would have been setting again via jQuery the property instead of invalidating it.

**Comment by djsutho** [comment]
Sorry for not getting back earlier. I should be able to look at this next week.

**Comment by djsutho** [comment]
Thanks for the work.I'll release this shortly.

**Comment by djsutho** [comment]
This has now been released.

**Comment by laffuste** [comment]
Thanks!!

**Pull request merged**
